# Generated by Django 4.2.16 on 2026-05-28 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_by', models.CharField(max_length=255)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('PARTIAL_SUCCESS', 'PARTIAL_SUCCESS')], default='PROCESSING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.company')),
            ],
        ),
        migrations.CreateModel(
            name='FailedRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('error_message', models.TextField()),
                ('raw_content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.dataupload')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'SCOPE_1'), ('SCOPE_2', 'SCOPE_2'), ('SCOPE_3', 'SCOPE_3')], max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
                ('raw_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_value', models.FloatField()),
                ('activity_unit', models.CharField(max_length=50)),
                ('normalization_notes', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('parser_version', models.CharField(default='v1', max_length=100)),
                ('co2e_kg', models.FloatField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FLAGGED', 'FLAGGED')], default='PENDING', max_length=20)),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('source_row_id', models.CharField(max_length=255)),
                ('is_locked', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.company')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.dataupload')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('APPROVE', 'APPROVE'), ('REJECT', 'REJECT'), ('EDIT', 'EDIT')], max_length=50)),
                ('performed_by', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissionrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['company'], name='emissions_e_company_43ac30_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['upload'], name='emissions_e_upload__581b61_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['review_status'], name='emissions_e_review__5517f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='emissionrecord',
            constraint=models.UniqueConstraint(fields=('upload', 'source_row_id'), name='unique_upload_source_row'),
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['company'], name='emissions_d_company_1a86c7_idx'),
        ),
    ]
